services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass password
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  couchbase:
    image: couchbase:latest
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: admin
      COUCHBASE_ADMINISTRATOR_PASSWORD: securepassword
    volumes:
      - couchbase_data:/opt/couchbase/var
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/pools" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command: >
      /bin/bash -c "/entrypoint.sh couchbase-server &
      until curl -s http://localhost:8091/pools > /dev/null; do echo 'Waiting for Couchbase...'; sleep 5; done &&
      echo 'Couchbase is ready, initializing cluster...' &&
      sleep 60 &&
      couchbase-cli cluster-init -c localhost:8091 --cluster-username admin --cluster-password securepassword --cluster-name tagbot --services data,index,query,fts &&
      couchbase-cli bucket-create -c localhost:8091 -u admin -p securepassword --bucket tagbot --bucket-type couchbase --bucket-ramsize 256"



volumes:
  redis_data:
  couchbase_data:
